### ISSUE TITLE
question about permissions

### ISSUE THREAD

**Issue by MyDogTom** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#1]
Hi.
Why is plugin need permission: "Read and change all data on websites you visit"?
Is it possible to have only "Read and change data on translate.google.com"? (or something like this)

**Comment by yamayamayamaji** [comment]
Hi, thank you for a question.

I want to do so but ...

URL of google translate website is not only

* "translate.google.com"

but also

* "translate.google.ca"
* "translate.google.de"
* "translate.google.nl"
* "translate.google.ru"

etc...

and this plugin is necessary to work on these URLs.

So I specified content_scripts field like this in the manifest.json.
```json
  "content_scripts": [ {
    ...
    "matches": ["*://*/*"],
    "include_globs": ["*://translate.google.*/*"],
    ...
  } ],
```

I think this means that the plugin work only when URL matches "*://translate.google.*/*".
[Match patterns and globs](https://developer.chrome.com/extensions/content_scripts#match-patterns-globs)
> The content script will be injected into a page if its URL matches any matches pattern and any include_globs pattern, as long as the URL doesn't also match an exclude_matches or exclude_globs pattern. Because the matches property is required, exclude_matches, include_globs, and exclude_globs can only be used to limit which pages will be affected.

But Chrome brings up the following warning:
"Read and modify all your data on all websites you visit"
because a "content_scripts" field with a "matches" entry that matches all hosts.


If possible, I want to specify "matches" field like
```json
    "matches": ["*://translate.google.*/*"],
```
but this is impossible according to rule of [match patterns](https://developer.chrome.com/extensions/match_patterns).
> If '*' is in the host, it must be the first character

:pensive:

**Comment by MyDogTom** [comment]
Now it is clear. Thank you for your answer and for the great extension!

**Comment by evansendra** [comment]
Thanks for linking me here from the support tab...props to you for making the effort to minimize scope of permissions.  Sucks that there's no wildcard for big company's like google who own many TLDs.

While it would be nothing more than a major pain-in-the-ass, I'd say you should probably still explicitly list all the TLDs in the manifest just so users don't get scared off by the "change all the data on all the sites you visit" perm.  For all the TLDs you'd have to list, see here:

https://en.wikipedia.org/wiki/List_of_Google_domains

**Comment by yamayamayamaji** [comment]
Nice advice.
That makes sense :smile:

I will try to list all TLDs.

**Comment by yamayamayamaji** [comment]
released ver2.0.3.0 .

- update manifest -> content_scripts -> matches  
list all the TLDs listed [wiki List_of_Google_domains](https://en.wikipedia.org/wiki/List_of_Google_domains)

- remove "tabs" permission  
it causes permission warning "Read your browsing history".  ([see](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/au_qakYSWkk))
reimplement showPageIcon feature using [chrome.declarativeContent](https://developer.chrome.com/extensions/declarativeContent#type-PageStateMatcher)
