### ISSUE TITLE
Language dropdown shortcut and language swap shortcut not working

### ISSUE THREAD

**Issue by dasyad00** [yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate#23]
![image](https://github.com/yamayamayamaji/Keyboard-Shortcuts-for-Google-Translate/assets/19555626/32f2b889-1065-4897-b504-ef0bce365714)

Expected:

- source language dropdown accessible via alt+8
- target language dropdown accessible via alt+9
- swap language accessible via alt+0

**Comment by K0stov** [comment]
[This newer, simpler plugin](https://github.com/JiaLong0209/google-translate-keyboard-shortcuts) doesn’t have the language dropdowns, nor are the controls customizable, but it can swap languages.

I will be using it instead of the current one. I’ve also made a pull request to add a shortcut for copying the outpust text.

**Comment by yamayamayamaji** [comment]
fixed.
